### ISSUE TITLE
如何关闭 enablePrintLog  

### ISSUE THREAD

**Issue by supermebing** [flutterplugin/dio_log#10]
///是否打印日志到控制台
  static bool enablePrintLog = true;
有如下打印 请问 如何关闭这个选项 
if (enablePrintLog) {
      NetOptions log = LogPoolManager.getInstance().logMap[resOpt.id.toString()]!;
      print('dio_log: request: url:${log.reqOptions?.url}');
      print('dio_log: request: method:${log.reqOptions?.method}');
      print('dio_log: request: params:${log.reqOptions?.params}');
      print('dio_log: request: duration:${getTimeStr1(log.reqOptions!.requestTime!)}');
      print('dio_log: response: ${toJson(log.resOptions?.data)}');
    }

**Comment by 519430378qqcom** [comment]
DioLogInterceptor.enablePrintLog = false;
dio.interceptors.add(DioLogInterceptor());
