### ISSUE TITLE
Incompatible with the latest dio stable version

### ISSUE THREAD

**Issue by zhanghuanchong** [flutterplugin/dio_log#3]
The current dio stable version is `dio: ^4.0.0`.

Installing the version `1.3.5` will cause: 

> Because dio_log 1.3.5 depends on dio ^3.0.0 and no versions of dio_log match >1.3.5 <2.0.0, dio_log ^1.3.5 requires dio ^3.0.0.

**Comment by zhanghuanchong** [comment]
You may need to merge the PR: #2

**Comment by 519430378qqcom** [comment]
It has been modified as follows
* Dio 4.0.0 support.
* Migrated to Flutter 2.
* Migrated to null safety
