### ISSUE TITLE
当复制json里面的null时，程序会闪退

### ISSUE THREAD

**Issue by likeSo** [flutterplugin/dio_log#5]
如题所示，当长按复制一个null值时，程序会闪退，猜测是原生代码里面没有判空导致的

**Comment by 519430378qqcom** [comment]
您使用的是哪个版本，试试更新了空安全版本的插件ok吗

**Comment by likeSo** [comment]
> 您使用的是哪个版本，试试更新了空安全版本的插件ok吗

我现在使用的是最新版本的，你新增了返回header展示的那个版本，该问题依然存在。闪退一半是原生代码的部分，可能是向原生传值后没有判空导致的。
另外关于返回内容显示header：最好也加上长按复制某一个字段的功能，谢谢

**Comment by likeSo** [comment]
报错信息：`Thread 1: "-[_UIConcretePasteboard setString:]: Argument is not an object of type NSString [NSNull]"`
给剪切板赋值的时候需要判空，需要把NSNull处理成空字符串或者"null"
/Users/XXX/Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio_log-2.0.1/lib/widget/json_view.dart:253
当value为空时，这里调用`Clipboard.setData(ClipboardData(text: value?.toString()));`会闪退。value?.toString()的结果仍然是null。

**Comment by 519430378qqcom** [comment]
我刚刚更新的版本，解决了你说的两个问题
