### ISSUE TITLE
Flutter 3.0 : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. 

### ISSUE THREAD

**Issue by nEdAy** [flutterplugin/dio_log#7]
Describe the bug

Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

Version (please complete the following information):

Flutter Version: Flutter 3.0.0 • channel stable
OS: Android

**Comment by 519430378qqcom** [comment]
更新了2.0.3版本

**Comment by nEdAy** [comment]
Everything is all right！
