### ISSUE TITLE
buildError : need WidgetsBinding.instance?

### ISSUE THREAD

**Issue by artem-2024** [flutterplugin/dio_log#9]
overlay_draggable_button.dart 
line 4
flutter channel : 2.8.1

**Comment by 519430378qqcom** [comment]
please use dio_log: 2.0.1

**Comment by 519430378qqcom** [comment]
please use 2.0.4
[v2.0.4] - 2022/07/11
* remove WidgetsBinding.instance.addPostFrameCallback was replaced by await Future.delayed(Duration(milliseconds: 500));
